const icons={
  ai:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><circle cx="4" cy="6" r="1.5"/><circle cx="20" cy="6" r="1.5"/><circle cx="4" cy="18" r="1.5"/><circle cx="20" cy="18" r="1.5"/><path d="M8.5 9.5 5.3 6.8m10.2 2.7 3.2-2.7m-10.2 7.7-3.2 2.7m10.2-2.7 3.2 2.7"/></svg>',
  chip:'<svg viewBox="0 0 24 24"><rect x="6" y="6" width="12" height="12" rx="2"/><rect x="9" y="9" width="6" height="6"/><path d="M9 2v4m6-4v4M9 18v4m6-4v4M2 9h4m-4 6h4m12-6h4m-4 6h4"/></svg>',
  health:'<svg viewBox="0 0 24 24"><path d="M8 3c6 4 2 14 8 18M16 3C10 7 14 17 8 21M9 7h6m-7 5h8m-7 5h6"/></svg>',
  car:'<svg viewBox="0 0 24 24"><path d="m4 15 2-6h12l2 6v4h-2v-2H6v2H4zM7 9l2-3h6l2 3"/><circle cx="8" cy="14" r="1"/><circle cx="16" cy="14" r="1"/></svg>',
  robot:'<svg viewBox="0 0 24 24"><rect x="5" y="7" width="14" height="12" rx="3"/><path d="M12 3v4M3 12h2m14 0h2M9 15h6"/><circle cx="9" cy="11" r="1"/><circle cx="15" cy="11" r="1"/></svg>',
  terminal:'<svg viewBox="0 0 24 24"><rect x="5" y="2" width="14" height="20" rx="3"/><path d="M9 5h6m-4 14h2M8 9h8v6H8z"/></svg>',
  space:'<svg viewBox="0 0 24 24"><path d="M14 4c3 1 5 3 6 6l-5 5-6-6zM9 9l-4 2-2 4 6-1m6 1-1 6 4-2 2-4"/><path d="m7 17-3 3m6-2-2 3"/></svg>',
  energy:'<svg viewBox="0 0 24 24"><path d="M13 2 5 14h6l-1 8 9-13h-6z"/></svg>',
  embodied:'<svg viewBox="0 0 24 24"><circle cx="12" cy="5" r="3"/><path d="M8 21v-5l-3-3 2-3 3 2h4l3-2 2 3-3 3v5m-8-5h8"/></svg>',
  brain:'<svg viewBox="0 0 24 24"><path d="M12 5a4 4 0 0 0-7 3 4 4 0 0 0 0 7 4 4 0 0 0 7 3V5Zm0 0a4 4 0 0 1 7 3 4 4 0 0 1 0 7 4 4 0 0 1-7 3"/><path d="M8 8v8m8-8v8M5 12h3m8 0h3"/></svg>',
  life:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M5 21c1-5 3-7 7-7s6 2 7 7M3 5h3M18 5h3M12 1v3"/></svg>'
};
const industries=[['ai','人工智能','#4F7CFF','#F5F7FF'],['chip','集成电路','#725BFF','#F7F5FF'],['health','医药健康','#10A77A','#F3FBF7'],['car','智能网联汽车','#0E79C9','#F3F9FC'],['robot','机器人','#126B85','#F3F9FA'],['terminal','智能终端','#2D6DDF','#F4F8FF'],['space','空天技术','#21417D','#F4F6FA'],['energy','先进能源','#0A9564','#F6FAF1'],['embodied','具身智能','#4956D8','#F5F5FF'],['brain','脑机接口','#8D4FDB','#FAF5FC'],['life','数字生命','#A13F92','#FCF4FA']];
const industryGroups=[
  {code:'1',title:'核心牵引产业',ids:['ai']},
  {code:'3',title:'优势主导产业',ids:['chip','health','car']},
  {code:'4',title:'新兴支柱产业',ids:['robot','terminal','space','energy']},
  {code:'N',title:'未来产业',ids:['embodied','brain','life']}
];
const policies=[['国家级','高新技术企业认定及税收优惠政策','企业所得税减按 15% 税率征收，研发费用可按规定加计扣除。',96,'长期有效'],['北京市','北京市科技型中小企业技术创新资金','支持企业开展关键核心技术攻关和科技成果转化，单项最高支持 500 万元。',92,'2026.09.30'],['区级','高层次科技人才引进与培养支持办法','为符合条件的高层次人才提供奖励、住房及团队建设支持。',88,'滚动申报'],['北京市','首台（套）重大技术装备示范应用项目','支持创新产品首试首用，按项目实际投入给予一定比例补助。',85,'2026.10.18']];
const enterpriseLibrary=[
  {name:'北京亦庄机器人科技有限公司',industry:'机器人与具身智能'},
  {name:'北京经开人工智能科技有限公司',industry:'人工智能'},
  {name:'北京亦庄集成电路有限公司',industry:'集成电路'},
  {name:'北京经开医药健康科技有限公司',industry:'医药健康'},
  {name:'北京亦庄智能网联汽车有限公司',industry:'智能网联汽车'},
  {name:'北京经开先进能源科技有限公司',industry:'先进能源'},
  {name:'北京亦庄空天科技有限公司',industry:'空天技术'},
  {name:'北京经开智能终端科技有限公司',industry:'智能终端'}
];
const $=s=>document.querySelector(s),selected=new Set();
let reports=JSON.parse(localStorage.getItem('policyReportsH5')||'[]').map(r=>({...r,status:r.status==='generating'&&r.readyAt&&Date.now()>=r.readyAt?'completed':r.status||'completed',companyName:r.companyName||'企业名称'})),currentReport=null,detailFrom='home',generationInterval=null,generationTimeout=null,subjectType='personal',wechatIdentity=JSON.parse(localStorage.getItem('policyWechatIdentityH5')||'null'),selectedEnterprise='';
wechatIdentity={...(wechatIdentity||{}),nickname:'🌛',openid:wechatIdentity?.openid||`preview_${Date.now()}`};localStorage.setItem('policyWechatIdentityH5',JSON.stringify(wechatIdentity));
const getIndustry=id=>industries.find(i=>i[0]===id);
const show=id=>{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo(0,0)};
const statusMap={completed:'已完成',generating:'生成中',failed:'失败'};
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
$('#industries').innerHTML=industryGroups.map(group=>`<section class="industry-group"><div class="industry-group-head"><span>${group.code}</span><b>${group.title}</b></div><div class="industry-group-grid">${group.ids.map(id=>{const i=getIndustry(id);return `<article class="industry" data-id="${i[0]}" style="--theme:${i[2]};--soft:${i[3]}"><div class="icon">${icons[i[0]]}</div><h3>${i[1]}</h3><span class="check">✓</span></article>`}).join('')}</div></section>`).join('');
const updateGenerateState=()=>{const hasIdentity=subjectType==='personal'?Boolean(wechatIdentity):Boolean(selectedEnterprise),ready=hasIdentity&&selected.size>0;$('#generate').disabled=!ready;$('#generate').textContent=!hasIdentity?(subjectType==='personal'?'请先获取微信信息':'请从企业库选择企业'):!selected.size?'请至少选择一个产业':'生成专属政策清单 →'};
const renderIdentity=()=>{document.querySelectorAll('[data-subject]').forEach(button=>button.classList.toggle('active',button.dataset.subject===subjectType));$('#personalIdentity').classList.toggle('is-hidden',subjectType!=='personal');$('#enterpriseIdentity').classList.toggle('is-hidden',subjectType!=='enterprise');$('#wechatAccount').classList.toggle('is-hidden',!wechatIdentity);$('#authorizeWechat').classList.toggle('is-hidden',Boolean(wechatIdentity));if(wechatIdentity){$('#wechatNickname').textContent=wechatIdentity.nickname||'';$('#wechatNickname').hidden=!wechatIdentity.nickname}updateGenerateState()};
document.querySelectorAll('[data-subject]').forEach(button=>button.onclick=()=>{subjectType=button.dataset.subject;$('#enterpriseResults').classList.add('is-hidden');renderIdentity()});
$('#authorizeWechat').onclick=()=>{wechatIdentity={nickname:'🌛',openid:`preview_${Date.now()}`};localStorage.setItem('policyWechatIdentityH5',JSON.stringify(wechatIdentity));renderIdentity()};
const renderEnterpriseResults=items=>{$('#enterpriseResults').innerHTML=items.map(item=>`<button data-enterprise="${escapeHtml(item.name)}"><span class="enterprise-result-icon">企</span><span><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.industry)}</small></span><i>›</i></button>`).join('');$('#enterpriseResults').classList.toggle('is-hidden',!items.length);document.querySelectorAll('[data-enterprise]').forEach(button=>button.onclick=()=>{selectedEnterprise=button.dataset.enterprise;$('#enterpriseSearch').value=selectedEnterprise;$('#enterpriseSearchWrap').classList.add('selected');$('#enterpriseResults').classList.add('is-hidden');updateGenerateState()})};
$('#enterpriseSearch').oninput=e=>{const keyword=e.target.value.trim().toLowerCase();if(e.target.value!==selectedEnterprise){selectedEnterprise='';$('#enterpriseSearchWrap').classList.remove('selected')}renderEnterpriseResults(keyword?enterpriseLibrary.filter(item=>item.name.toLowerCase().includes(keyword)||item.industry.toLowerCase().includes(keyword)).slice(0,6):[]);updateGenerateState()};
document.querySelectorAll('.industry').forEach(card=>card.onclick=()=>{selected.has(card.dataset.id)?selected.delete(card.dataset.id):selected.add(card.dataset.id);card.classList.toggle('selected');$('#count').textContent=`已选 ${selected.size} 项`;updateGenerateState()});
$('#generate').onclick=()=>{const companyName=subjectType==='personal'?(wechatIdentity?.nickname||'个人用户'):selectedEnterprise;if(!companyName||!selected.size)return;const chosen=industries.filter(i=>selected.has(i[0]));const now=new Date();currentReport={id:String(Date.now()),companyName,subjectType,industries:chosen.map(i=>i[0]),createdAt:now.toLocaleString('zh-CN',{hour12:false}),total:18+chosen.length*3,status:'generating',readyAt:Date.now()+60000};reports.unshift(currentReport);localStorage.setItem('policyReportsH5',JSON.stringify(reports));$('#selectedTags').innerHTML=chosen.map(i=>`<span>● ${i[1]}</span>`).join('');$('#industrySelect').classList.add('is-hidden');$('#homeContent').classList.add('generating-mode');$('#inlineGenerating').classList.add('active');$('#inlineGenerating').classList.remove('complete');$('#inlineTitle').innerHTML='正在为您生成<br>专属政策清单…';$('#inlineSub').innerHTML='报告生成预计需要 1 分钟，您可先退出，<br>稍后前往「我的报告」查看生成结果。';$('#progressText').textContent='正在为您生成专属政策清单';let p=8;generationInterval=setInterval(()=>{p+=Math.max(1,Math.round((100-p)*.075));p=Math.min(p,99);$('#progress').style.width=p+'%';$('#percent').textContent=p+'%'},220);generationTimeout=setTimeout(()=>{clearInterval(generationInterval);currentReport.status='completed';localStorage.setItem('policyReportsH5',JSON.stringify(reports));$('#progress').style.width='100%';$('#percent').textContent='100%';$('#progressText').textContent='专属政策清单已生成';detailFrom='home';renderReport(currentReport);$('#inlineTitle').innerHTML='专属政策清单<br>已生成';$('#inlineSub').textContent='智能匹配与政策分析已完成，可查看完整政策清单。';$('#inlineGenerating').classList.add('complete')},5200)};
const resetGeneration=()=>{$('#industrySelect').classList.remove('is-hidden');$('#homeContent').classList.remove('generating-mode');$('#inlineGenerating').classList.remove('active','complete');$('#progress').style.width='8%';$('#percent').textContent='8%';$('#progressText').textContent='正在为您生成专属政策清单'};
$('#cancelGeneration').onclick=()=>{clearInterval(generationInterval);clearTimeout(generationTimeout);resetGeneration()};
$('#viewGenerated').onclick=()=>{show('detail');resetGeneration()};
function renderReport(report){currentReport=report;$('#longReportTitle').textContent='政策清单'}
function downloadReport(report){const chosen=report.industries.map(getIndustry),safeName=report.companyName.replace(/[\\/:*?"<>|]/g,'-'),a=document.createElement('a');a.href='./assets/reports/embodied-intelligence-policy-long-v3.jpg';a.download=`${safeName}-${chosen[0][1]}产业政策清单长图.jpg`;a.click()}
function renderHistory(){reports=reports.map(r=>r.status==='generating'&&r.readyAt&&Date.now()>=r.readyAt?{...r,status:'completed'}:r);localStorage.setItem('policyReportsH5',JSON.stringify(reports));const root=$('#reports');root.classList.toggle('has-reports',reports.length>0);$('#reportCount').textContent=`${reports.length} 份`;$('#historyList').innerHTML=reports.map(r=>{const chosen=r.industries.map(getIndustry),main=chosen[0],status=r.status||'completed';return `<article class="history-card" data-report="${r.id}" style="--theme:${main[2]}"><div class="history-cover"><div class="icon">${icons[main[0]]}</div><b>POLICY<br>REPORT</b></div><div class="history-info"><div class="history-info-head"><h3>${escapeHtml(r.companyName)} · ${main[1]}产业政策清单</h3><span class="history-status status-${status}">${statusMap[status]}</span></div><div class="history-tags">${chosen.map(i=>`<span>${i[1]}</span>`).join('')}</div><p>${r.createdAt} · ${r.total} 项政策</p><div class="history-actions"><button class="history-download" data-report="${r.id}">⇩ 下载</button><button class="history-delete" data-report="${r.id}">删除</button></div></div></article>`}).join('');document.querySelectorAll('.history-card').forEach(card=>card.onclick=()=>{const report=reports.find(r=>r.id===card.dataset.report);if(report.status!=='completed'){alert(`当前报告状态：${statusMap[report.status]}`);return}detailFrom='reports';renderReport(report);show('detail')});document.querySelectorAll('.history-download').forEach(btn=>btn.onclick=e=>{e.stopPropagation();const report=reports.find(r=>r.id===btn.dataset.report);if(report.status!=='completed'){alert('报告尚未生成完成，暂不能下载');return}downloadReport(report)});document.querySelectorAll('.history-delete').forEach(btn=>btn.onclick=e=>{e.stopPropagation();if(!confirm('确认删除这份政策报告吗？'))return;reports=reports.filter(r=>r.id!==btn.dataset.report);localStorage.setItem('policyReportsH5',JSON.stringify(reports));renderHistory()})}
$('#myReports').onclick=()=>{renderHistory();show('reports')};$('#reportsBack').onclick=()=>show('home');$('#newReport').onclick=$('#emptyCreate').onclick=()=>show('home');$('#backHome').onclick=()=>show(detailFrom);$('#download').onclick=()=>downloadReport(currentReport);
renderIdentity();
